version: '3'

services:
  database:
    image: "postgres:14"
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - data1:/var/lib/postgresql/data/
    networks:
      - dev-network

volumes:
  data1:

networks:
  dev-network:
    driver: bridge

