version: '2.2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./initdb.d:/docker-entrypoint-initdb.d
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - dev-network
    command: ["-f", "/etc/mongod.conf"]

volumes:
  mongodb-data:
  mongodb-log:

networks:
  dev-network:
    driver: bridge

