version: '2.2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./initdb.d:/docker-entrypoint-initdb.d
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_USERNAME: dev
      MONGO_INITDB_PASSWORD: password
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "27017:27017"
    networks:
      - dev-network
    command: ["-f", "/etc/mongod.conf"]

volumes:
  mongodb-data:
  mongodb-log:

networks:
  dev-network:
    driver: bridge

