version: '3.3'

services:
  database:
    image: mysql:5.7.36
    container_name: mysql
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - data1:/var/lib/mysql
    networks:
      - dev-network

volumes:
  data1:

networks:
  dev-network:
    driver: bridge
