version: "3.2"

services:
  redis:
    image: "redis:6.2.6"
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - data1:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_REPLICATION_MODE: master
    networks:
      - dev-network

volumes:
  data1:

networks:
  dev-network:
    driver: bridge